--- 
title: "CA4 RDBMS - Query Database"
author: "Gareth Burger"
subtitle: "Querying a SQLite database"
date: "`r format(Sys.time(), '%a, %d %B %y')`"
always_allow_html: true
output:
  html_document:
    toc: yes
    toc_title: Table Of Contents
    toc_float: yes
    toc_depth: 3
    fig_caption: no
    lof: yes
    number_sections: yes
    code_folding: hide
    theme: paper
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
fontsize: 10pt
---

```{r setup and library load, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# clear console on each execute and set chunk default to not show code
cat('\014')
```

---

```{r}
# download and load libraries
if(!require("DBI"))
  install.packages("DBI")
if(!require("dplyr"))
  install.packages("dplyr")
if(!require("readr"))
  install.packages("readr")

library(DBI)
library(dplyr)
library(readr)

# connect (and create) a new local SQLite DB

conn <- dbConnect(RSQLite::SQLite(), "mtcars_db.sqlite")

mtcars

# Add table data to the SQLite DB

dbWriteTable(conn, "mtcars", mtcars, overwrite = T, append = F)

# Test the DB

# View(mtcars)

dbListTables(conn)
dbListFields(conn, "mtcars")

# Query and store the results

# CRUD - Create, Rename, Update, Delete

# result <-  dbGetQuery(conn, "SELECT * FROM mtcars")
# result

# result <-  dbGetQuery(conn, "SELECT wt, disp, mpg FROM mtcars")
# result

# result <-  dbGetQuery(conn, "SELECT * FROM mtcars WHERE mpg >= 18 AND mpg <= 22")
# result

# result <-  dbGetQuery(conn, "SELECT * FROM mtcars WHERE mpg >= 18 AND mpg <= 22 ORDER BY hp ASC LIMIT 4")
# result

# result <-  dbGetQuery(conn, "SELECT * FROM mtcars WHERE mpg >= 18 AND mpg <= 22 ORDER BY hp ASC LIMIT 4")
# result

# result <-  dbGetQuery(conn, "SELECT COUNT(mpg) FROM mtcars WHERE mpg > 25")
# result
# 
# result <-  dbGetQuery(conn, "SELECT AVG(hp) FROM mtcars")
# result

# Execute a query with no result

result <-  dbGetQuery(conn, "SELECT * FROM mtcars")
result

dbExecute(conn, "DELETE FROM mtcars WHERE mpg <= 20")

result <-  dbGetQuery(conn, "SELECT * FROM mtcars")
result

# Do NOT forget to disconnect - otherwise we may hit a remote connection limit

dbDisconnect(conn)
```