--- 
title: "CA4 RDBMS - Generate Database"
author: "Gareth Burger"
subtitle: "Generating a SQLite database"
date: "`r format(Sys.time(), '%a, %d %B %y')`"
always_allow_html: true
output:
  html_document:
    toc: yes
    toc_title: Table Of Contents
    toc_float: yes
    toc_depth: 3
    fig_caption: no
    lof: yes
    number_sections: yes
    code_folding: hide
    theme: paper
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
fontsize: 10pt
---

```{r setup and library load, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
# clear console on each execute and set chunk default to not show code
cat('\014')
```

# https://www.tutorialspoint.com/sql/sql-rdbms-concepts.htm

```{r}
# download and load libraries
if(!require("DBI"))
  install.packages("DBI")
if(!require("dplyr"))
  install.packages("dplyr")
#if(!require("readr"))
#  install.packages("readr")

library(DBI)
library(dplyr)
#library(readr)

# connect (and create) a new local SQLite DB

conn <- dbConnect(RSQLite::SQLite(), "mtcars_db.sqlite")

# add table data to the SQLite db

dbWriteTable(conn, "mtcars", mtcars, overwrite = T, append = F)

# test the DB

#View(mtcars)

# list the tables
dbListTables(conn)
# list the fields in the named table
dbListFields(conn, "mtcars")

# query and store the results

# CRUD - Create, Rename, Update, Delete

# select all data from all columns from table
result <-  dbGetQuery(conn, "SELECT * FROM mtcars")
result

# select data from specific columns from table
result <-  dbGetQuery(conn, "SELECT wt, disp, mpg FROM mtcars")
result

result$wt[0]
# show first 5 results
head(result, 5)
# show last 10 results
tail(result, 10)

result <-  dbGetQuery(conn, "SELECT * FROM mtcars WHERE mpg >= 18 AND mpg <= 22")
result

result <-  dbGetQuery(conn, "SELECT * FROM mtcars WHERE mpg >= 18 AND mpg <= 22 ORDER BY hp ASC LIMIT 4")
result

result <-  dbGetQuery(conn, "SELECT * FROM mtcars WHERE mpg >= 18 AND mpg <= 22 ORDER BY hp DESC LIMIT 4")
result

result <-  dbGetQuery(conn, "SELECT COUNT(mpg) FROM mtcars WHERE mpg > 25")
result

result <-  dbGetQuery(conn, "SELECT AVG(hp) FROM mtcars")
result

# execute a query with no result
dbExecute(conn, "DELETE FROM mtcars WHERE mpg <= 20")

result <-  dbGetQuery(conn, "SELECT * FROM mtcars")
result

# do not forget to disconnect - otherwise we may hit a remote connection limit
dbDisconnect(conn)
```