---
title: "CA 4: Part A - Database Design & SQL Querying"
author: "Gareth Burger"
date: "January, 2023"
output:
  pdf_document: default
  html_document:
    code_folding: show
subtitle: R and SQL code to query a SQLite database
---

```{r Setup and Library Load, include=FALSE}
# clear console on each execute and set chunk default to not show code
cat('\014')

if(!require("RSQLite"))
  install.packages("RSQLite")
if(!require("knitr"))
  install.packages("RSQLite")

library(RSQLite)
library(knitr)
```

---

## Connect to SQLite Database
```{r}
# connect to the local SQLite database
conn <- dbConnect(RSQLite::SQLite(), dbname = "daie_ca4_data.sqlite")
```

---

# Database Queries

### 1. SELECT with WHERE, LIKE, and OR
```{r}
# select data from table using where, like and or clauses
result <- dbGetQuery(conn, "SELECT first_name, last_name
                            FROM team_member
                            WHERE last_name LIKE '%oo%'
                            OR first_name LIKE '%ia%'")

# display the results in a table using kable (in knitr package)
kable(result, 
      col.names = c("First Name", "Last Name"), 
      caption = "List of Team Members with Names Containing 'oo' or 'ia'")
```

---

### 2. SELECT with DISTINCT and ORDER BY
```{r}
# select data from table using distinct and order by
result <- dbGetQuery(conn, "SELECT DISTINCT asset_type
                            FROM asset
                            ORDER BY asset_type")

# display the results in a table using kable (in knitr package)
kable(result, 
      col.names = c("Asset Types"), 
      caption = "List of Distinct Asset Types")
```

---

### 3. Inner Join
```{r}
# select data from tables using an inner join
result <- dbGetQuery(conn, "SELECT asset_description, asset_type, project_name
                            FROM asset
                            INNER JOIN project
                            ON asset.project_id = project.id")

# display the results in a table using kable (in knitr package)
kable(result, 
      col.names = c("Asset Description", "Asset Type", "Project Name"), 
      caption = "List of Assets and associated Projects")
```

---

### 4. Subquery with SELECT
```{r}
# select data from tables using a select subquery
result <- dbGetQuery(conn, "SELECT first_name, last_name, role_name
                            FROM team_member
                            INNER JOIN role
                            ON team_member.role_id = role.id
                            WHERE team_id IN (SELECT team_id
                                  FROM team_member
                                  WHERE team_id = 2)")

# display the results in a table using kable (in knitr package)
kable(result, 
      col.names = c("First Name", "Last Name", "Role"), 
      caption = "List of Team Members in Team 2")
```

---

### 5. SELECT across a Date Range
```{r}
# select data from table between a range of dates
result <- dbGetQuery(conn, "SELECT project_name, delivery_date
                            FROM project
                            WHERE delivery_date >= '2023-01-01'
                            AND delivery_date <= '2023-06-30'")

# display the results in a table using kable (in knitr package)
kable(result, 
      col.names = c("Project Name", "Delivery Date"), 
      caption = "List of Projects due by end of Q2 2023")
```

---

### Close Database Connection
```{r Disconnect}
# close the connection to the database to avoid hitting a connection limit
dbDisconnect(conn)
```